/* Motion Studio: small canvas-first architecture, designed for future media/vector tracks. */
const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const W=800,H=500, blank=()=>{const c=document.createElement('canvas');c.width=W;c.height=H;return c.toDataURL()};
const state={name:'Untitled animation',fps:12,frames:[],frame:0,layer:0,tool:'brush',color:'#7868ff',size:8,zoom:1,onion:false,playing:false,history:[],future:[]};
const draw=$('#drawCanvas'), onion=$('#onionCanvas'), ctx=draw.getContext('2d'), octx=onion.getContext('2d'); draw.width=onion.width=W;draw.height=onion.height=H;
const newFrame=()=>({layers:[{name:'Layer 1',visible:true,image:blank()}]});
state.frames=[newFrame()];
function active(){return state.frames[state.frame]} function layer(){return active().layers[state.layer]}
function image(src){return new Promise(resolve=>{const i=new Image;i.onload=()=>resolve(i);i.src=src})}
async function render(){
  // The lower canvas contains non-active layers/onion skin; the upper canvas is
  // the active raster layer and is the only surface that pointer editing changes.
  octx.clearRect(0,0,W,H);
  for(let i=0;i<active().layers.length;i++) if(i!==state.layer&&active().layers[i].visible) octx.drawImage(await image(active().layers[i].image),0,0);
  const selected=layer();ctx.clearRect(0,0,W,H);if(selected.visible)ctx.drawImage(await image(selected.image),0,0);
  await renderOnion(); renderLayers();renderFrames(); $('#frameLabel').textContent=`Frame ${String(state.frame+1).padStart(2,'0')}`
}
async function renderOnion(){if(!state.onion||!state.frame)return;const prev=state.frames[state.frame-1];octx.save();octx.globalAlpha=.22;for(const l of prev.layers)if(l.visible)octx.drawImage(await image(l.image),0,0);octx.restore()}
function snapshot(){state.history.push(JSON.stringify(state.frames));if(state.history.length>30)state.history.shift();state.future=[]}
async function redrawLayer(){ctx.clearRect(0,0,W,H);for(const l of active().layers)if(l.visible)ctx.drawImage(await image(l.image),0,0)}
function renderLayers(){$('#layerList').innerHTML=active().layers.map((l,i)=>`<div class="layer-row ${i===state.layer?'active':''}" data-layer="${i}"><button class="eye" data-eye="${i}">${l.visible?'◉':'○'}</button><input value="${l.name}" aria-label="Layer name"></div>`).join('');$$('.layer-row').forEach(r=>r.onclick=e=>{if(e.target.tagName==='INPUT')return;state.layer=+r.dataset.layer;render()});$$('.eye').forEach(b=>b.onclick=e=>{e.stopPropagation();let l=active().layers[+b.dataset.eye];l.visible=!l.visible;render()});$$('.layer-row input').forEach((i,n)=>i.onchange=()=>{active().layers[n].name=i.value})}
async function renderFrames(){const strip=$('#frameStrip');strip.innerHTML='';for(let n=0;n<state.frames.length;n++){const b=document.createElement('button');b.className='frame '+(n===state.frame?'active':'');b.innerHTML=`<canvas width="72" height="65"></canvas><small>Frame ${n+1}</small>`;b.onclick=()=>{state.frame=n;state.layer=0;render()};strip.append(b);const x=b.querySelector('canvas').getContext('2d');for(const l of state.frames[n].layers)if(l.visible)x.drawImage(await image(l.image),0,0,72,65)}}
let drawing=false,start,last,base;
function point(e){const r=draw.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:(p.clientX-r.left)*W/r.width,y:(p.clientY-r.top)*H/r.height}}
function setupStroke(x){ctx.lineCap=ctx.lineJoin='round';ctx.lineWidth=state.size;ctx.strokeStyle=state.tool==='eraser'?'#fff':state.color;ctx.globalCompositeOperation=state.tool==='eraser'?'destination-out':'source-over';ctx.beginPath();ctx.moveTo(x.x,x.y)}
function paint(e){e.preventDefault();const p=point(e);if(!drawing){snapshot();drawing=true;start=last=p;base=draw.toDataURL();setupStroke(p);return}if(['brush','eraser'].includes(state.tool)){ctx.lineTo(p.x,p.y);ctx.stroke();last=p}else{image(base).then(i=>{ctx.clearRect(0,0,W,H);ctx.drawImage(i,0,0);setupStroke(start);if(state.tool==='line')ctx.lineTo(p.x,p.y);if(state.tool==='rect')ctx.strokeRect(start.x,start.y,p.x-start.x,p.y-start.y);if(state.tool==='circle'){let rx=p.x-start.x,ry=p.y-start.y;ctx.ellipse(start.x,start.y,Math.abs(rx),Math.abs(ry),0,0,Math.PI*2)}ctx.stroke()})}}
function finish(){if(!drawing)return;drawing=false;ctx.globalCompositeOperation='source-over';layer().image=draw.toDataURL();renderFrames()}
draw.addEventListener('pointerdown',e=>{draw.setPointerCapture(e.pointerId);paint(e)});draw.addEventListener('pointermove',e=>{if(drawing)paint(e)});draw.addEventListener('pointerup',finish);draw.addEventListener('pointercancel',finish);
$$('.tool[data-tool]').forEach(b=>b.onclick=()=>{state.tool=b.dataset.tool;$$('.tool').forEach(x=>x.classList.toggle('active',x===b))});
$('#color').oninput=e=>{state.color=e.target.value;$('#brushDot').style.background=state.color};$('#brushSize').oninput=e=>{state.size=+e.target.value;$('#sizeOutput').value=`${state.size} px`;$('#brushDot').style.width=$('#brushDot').style.height=Math.max(5,state.size)+'px'};
$('#undo').onclick=()=>{if(!state.history.length)return;state.future.push(JSON.stringify(state.frames));state.frames=JSON.parse(state.history.pop());state.layer=Math.min(state.layer,active().layers.length-1);render()};$('#redo').onclick=()=>{if(!state.future.length)return;state.history.push(JSON.stringify(state.frames));state.frames=JSON.parse(state.future.pop());render()};
$('#clearCanvas').onclick=()=>{snapshot();layer().image=blank();render()};$('#addLayer').onclick=()=>{snapshot();active().layers.unshift({name:`Layer ${active().layers.length+1}`,visible:true,image:blank()});state.layer=0;render()};
function addFrame(copy=false){snapshot();let f=copy?JSON.parse(JSON.stringify(active())):newFrame();state.frames.splice(state.frame+1,0,f);state.frame++;state.layer=0;render()}$('#addFrame').onclick=()=>addFrame();$('#duplicateFrame').onclick=()=>addFrame(true);$('#deleteFrame').onclick=()=>{if(state.frames.length===1)return toast('Keep at least one frame');snapshot();state.frames.splice(state.frame,1);state.frame=Math.max(0,state.frame-1);state.layer=0;render()};$('#prevFrame').onclick=()=>{state.frame=(state.frame-1+state.frames.length)%state.frames.length;render()};$('#nextFrame').onclick=()=>{state.frame=(state.frame+1)%state.frames.length;render()};
$('#fps').onchange=e=>state.fps=Math.max(1,Math.min(30,+e.target.value||12));$('#onion').onchange=e=>{state.onion=e.target.checked;render()};
function zoom(n){state.zoom=Math.max(.35,Math.min(1.6,n));$('#stage').style.transform=`scale(${state.zoom})`;$('#zoomValue').textContent=Math.round(state.zoom*100)+'%'}$('#zoomIn').onclick=()=>zoom(state.zoom+.15);$('#zoomOut').onclick=()=>zoom(state.zoom-.15);$('#zoomReset').onclick=()=>zoom(1);
let timer;$('#play').onclick=()=>{state.playing=!state.playing;$('#play').textContent=state.playing?'❚❚':'▶';if(state.playing)timer=setInterval(()=>{$('#nextFrame').click()},1000/state.fps);else clearInterval(timer)};
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
$('#newProject').onclick=()=>{if(confirm('Start a new project?')){state.frames=[newFrame()];state.frame=state.layer=0;state.history=[];$('#projectName').value='Untitled animation';render()}};$('#projectName').oninput=e=>state.name=e.target.value;
$('#saveProject').onclick=()=>download(new Blob([JSON.stringify({version:1,name:$('#projectName').value,fps:state.fps,frames:state.frames})],{type:'application/json'}),`${$('#projectName').value||'animation'}.json`);
$('#importProject').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader;r.onload=()=>{try{const p=JSON.parse(r.result);if(!Array.isArray(p.frames))throw Error();state.frames=p.frames;state.fps=p.fps||12;$('#fps').value=state.fps;$('#projectName').value=p.name||'Imported animation';state.frame=state.layer=0;render();toast('Project imported')}catch{toast('That is not a Motion Studio project')}};r.readAsText(f)};
$('#exportFrames').onclick=async()=>{for(let n=0;n<state.frames.length;n++){const c=document.createElement('canvas'),x=c.getContext('2d');c.width=W;c.height=H;for(const l of state.frames[n].layers)if(l.visible)x.drawImage(await image(l.image),0,0);c.toBlob(b=>download(b,`${($('#projectName').value||'animation').replace(/[^a-z0-9]/gi,'-')}-frame-${String(n+1).padStart(2,'0')}.png`),'image/png');await new Promise(r=>setTimeout(r,250))}toast(`${state.frames.length} PNG frame(s) exported`)};
render();
